export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const RECIEVE_CHARACTERS = 'RECIEVE_CHARACTERS';

export const FETCH_CHARACTERS_COMICS = 'FETCH_CHARACTERS_COMICS';
export const RECIEVE_CHARACTERS_COMICS = 'RECIEVE_CHARACTERS_COMICS';

export const FETCH_CHARACTERS_STORIES = 'FETCH_CHARACTERS_STORIES';
export const RECIEVE_CHARACTERS_STORIES = 'RECIEVE_CHARACTERS_STORIES';
